### ISSUE TITLE
unable to edit entries in an uploaded dictionary

### ISSUE THREAD

**Issue by keshavdata** [ibm-cloud-docs/knowledge-studio#34]
As per the documentation (https://cloud.ibm.com/docs/services/knowledge-studio?topic=knowledge-studio-dictionaries), I created a dictionary and uploaded the file as a csv. 

But, this cannot file cannot be edited online and only the top 3 entries can be previewed

![image](https://user-images.githubusercontent.com/56116143/69055242-a1957280-0a0d-11ea-8b50-81005134aaeb.png)

According to the documentation, editing should be possible:
_(4) After importing or adding entries, you can edit the entries._

**Comment by jdicarl** [comment]
@keshavdata I assume this answer solved your problem. Please comment if not.
